# Generated by Django 4.1.1 on 2022-09-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('course', models.IntegerField(max_length=5)),
                ('college', models.CharField(choices=[('MED', 'Medical'), ('IT', 'Information Technologies'), ('JUR', 'Juridic')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('studies_from', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
