# Generated by Django 4.1.1 on 2022-09-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='passwrd', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.IntegerField(),
        ),
    ]
