# Generated by Django 4.1.1 on 2022-09-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_password_alter_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
